countries_to_site = {
    "aland islands": "https://deposit-pdbe.wwpdb.org/deposition",
    "vatican city": "https://deposit-pdbe.wwpdb.org/deposition",
    "holy see (vatican city state)": "https://deposit-pdbe.wwpdb.org/deposition",
    "switzerland": "https://deposit-pdbe.wwpdb.org/deposition",
    "andorra": "https://deposit-pdbe.wwpdb.org/deposition",
    "estonia": "https://deposit-pdbe.wwpdb.org/deposition",
    "iceland": "https://deposit-pdbe.wwpdb.org/deposition",
    "albania": "https://deposit-pdbe.wwpdb.org/deposition",
    "czech republic": "https://deposit-pdbe.wwpdb.org/deposition",
    "austria": "https://deposit-pdbe.wwpdb.org/deposition",
    "ireland": "https://deposit-pdbe.wwpdb.org/deposition",
    "spain": "https://deposit-pdbe.wwpdb.org/deposition",
    "greece": "https://deposit-pdbe.wwpdb.org/deposition",
    "netherlands": "https://deposit-pdbe.wwpdb.org/deposition",
    "portugal": "https://deposit-pdbe.wwpdb.org/deposition",
    "norway": "https://deposit-pdbe.wwpdb.org/deposition",
    "latvia": "https://deposit-pdbe.wwpdb.org/deposition",
    "lithuania": "https://deposit-pdbe.wwpdb.org/deposition",
    "luxembourg": "https://deposit-pdbe.wwpdb.org/deposition",
    "gibraltar": "https://deposit-pdbe.wwpdb.org/deposition",
    "romania": "https://deposit-pdbe.wwpdb.org/deposition",
    "poland": "https://deposit-pdbe.wwpdb.org/deposition",
    "belgium": "https://deposit-pdbe.wwpdb.org/deposition",
    "france": "https://deposit-pdbe.wwpdb.org/deposition",
    "bulgaria": "https://deposit-pdbe.wwpdb.org/deposition",
    "denmark": "https://deposit-pdbe.wwpdb.org/deposition",
    "croatia": "https://deposit-pdbe.wwpdb.org/deposition",
    "germany": "https://deposit-pdbe.wwpdb.org/deposition",
    "italy": "https://deposit-pdbe.wwpdb.org/deposition",
    "bosnia and herzegovina": "https://deposit-pdbe.wwpdb.org/deposition",
    "finland": "https://deposit-pdbe.wwpdb.org/deposition",
    "hungary": "https://deposit-pdbe.wwpdb.org/deposition",
    "belarus": "https://deposit-pdbe.wwpdb.org/deposition",
    "serbia": "https://deposit-pdbe.wwpdb.org/deposition",
    "montenegro": "https://deposit-pdbe.wwpdb.org/deposition",
    "moldova": "https://deposit-pdbe.wwpdb.org/deposition",
    "moldova, republic of": "https://deposit-pdbe.wwpdb.org/deposition",
    "faroe islands": "https://deposit-pdbe.wwpdb.org/deposition",
    "monaco": "https://deposit-pdbe.wwpdb.org/deposition",
    "cyprus": "https://deposit-pdbe.wwpdb.org/deposition",
    "macedonia": "https://deposit-pdbe.wwpdb.org/deposition",
    "slovakia": "https://deposit-pdbe.wwpdb.org/deposition",
    "malta": "https://deposit-pdbe.wwpdb.org/deposition",
    "slovenia": "https://deposit-pdbe.wwpdb.org/deposition",
    "san marino": "https://deposit-pdbe.wwpdb.org/deposition",
    "sweden": "https://deposit-pdbe.wwpdb.org/deposition",
    "united kingdom": "https://deposit-pdbe.wwpdb.org/deposition",
    "svalbard and jan mayen": "https://deposit-pdbe.wwpdb.org/deposition",
    "ukraine": "https://deposit-pdbe.wwpdb.org/deposition",
    "liechtenstein": "https://deposit-pdbe.wwpdb.org/deposition",
    "isle of man": "https://deposit-pdbe.wwpdb.org/deposition",
    "guernsey": "https://deposit-pdbe.wwpdb.org/deposition",
    "jersey": "https://deposit-pdbe.wwpdb.org/deposition",
    "russia": "https://deposit-pdbe.wwpdb.org/deposition",
    "russian federation": "https://deposit-pdbe.wwpdb.org/deposition",
    "georgia": "https://deposit-pdbe.wwpdb.org/deposition",
    "azerbaijan": "https://deposit-pdbe.wwpdb.org/deposition",
    "armenia": "https://deposit-pdbe.wwpdb.org/deposition",
    "israel": "https://deposit-pdbe.wwpdb.org/deposition",
    "cook islands": "https://deposit.wwpdb.org/deposition",
    "samoa": "https://deposit.wwpdb.org/deposition",
    "american samoa": "https://deposit.wwpdb.org/deposition",
    "palau": "https://deposit.wwpdb.org/deposition",
    "tuvalu": "https://deposit.wwpdb.org/deposition",
    "nauru": "https://deposit.wwpdb.org/deposition",
    "kiribati": "https://deposit.wwpdb.org/deposition",
    "marshall islands": "https://deposit.wwpdb.org/deposition",
    "micronesia": "https://deposit.wwpdb.org/deposition",
    "micronesia, federated states of": "https://deposit.wwpdb.org/deposition",
    "tonga": "https://deposit.wwpdb.org/deposition",
    "new zealand": "https://deposit.wwpdb.org/deposition",
    "australia": "https://deposit.wwpdb.org/deposition",
    "vanuatu": "https://deposit.wwpdb.org/deposition",
    "solomon islands": "https://deposit.wwpdb.org/deposition",
    "fiji": "https://deposit.wwpdb.org/deposition",
    "niue": "https://deposit.wwpdb.org/deposition",
    "tokelau": "https://deposit.wwpdb.org/deposition",
    "pitcairn": "https://deposit.wwpdb.org/deposition",
    "guam": "https://deposit.wwpdb.org/deposition",
    "french polynesia": "https://deposit.wwpdb.org/deposition",
    "new caledonia": "https://deposit.wwpdb.org/deposition",
    "united states minor outlying islands": "https://deposit.wwpdb.org/deposition",
    "wallis and futuna": "https://deposit.wwpdb.org/deposition",
    "northern mariana islands": "https://deposit.wwpdb.org/deposition",
    "norfolk island": "https://deposit.wwpdb.org/deposition",
    "papua new guinea": "https://deposit.wwpdb.org/deposition",
    "guinea-bissau": "https://deposit-pdbe.wwpdb.org/deposition",
    "zambia": "https://deposit-pdbe.wwpdb.org/deposition",
    "ivory coast": "https://deposit-pdbe.wwpdb.org/deposition",
    "western sahara": "https://deposit-pdbe.wwpdb.org/deposition",
    "equatorial guinea": "https://deposit-pdbe.wwpdb.org/deposition",
    "egypt": "https://deposit-pdbe.wwpdb.org/deposition",
    "congo": "https://deposit-pdbe.wwpdb.org/deposition",
    "congo, the democratic republic of the": "https://deposit-pdbe.wwpdb.org/deposition",
    "central african republic": "https://deposit-pdbe.wwpdb.org/deposition",
    "angola": "https://deposit-pdbe.wwpdb.org/deposition",
    "gabon": "https://deposit-pdbe.wwpdb.org/deposition",
    "ethiopia": "https://deposit-pdbe.wwpdb.org/deposition",
    "guinea": "https://deposit-pdbe.wwpdb.org/deposition",
    "gambia": "https://deposit-pdbe.wwpdb.org/deposition",
    "zimbabwe": "https://deposit-pdbe.wwpdb.org/deposition",
    "cape verde": "https://deposit-pdbe.wwpdb.org/deposition",
    "ghana": "https://deposit-pdbe.wwpdb.org/deposition",
    "rwanda": "https://deposit-pdbe.wwpdb.org/deposition",
    "tanzania": "https://deposit-pdbe.wwpdb.org/deposition",
    "tanzania, united republic of": "https://deposit-pdbe.wwpdb.org/deposition",
    "cameroon": "https://deposit-pdbe.wwpdb.org/deposition",
    "namibia": "https://deposit-pdbe.wwpdb.org/deposition",
    "niger": "https://deposit-pdbe.wwpdb.org/deposition",
    "nigeria": "https://deposit-pdbe.wwpdb.org/deposition",
    "tunisia": "https://deposit-pdbe.wwpdb.org/deposition",
    "liberia": "https://deposit-pdbe.wwpdb.org/deposition",
    "lesotho": "https://deposit-pdbe.wwpdb.org/deposition",
    "togo": "https://deposit-pdbe.wwpdb.org/deposition",
    "chad": "https://deposit-pdbe.wwpdb.org/deposition",
    "eritrea": "https://deposit-pdbe.wwpdb.org/deposition",
    "libya": "https://deposit-pdbe.wwpdb.org/deposition",
    "burkina faso": "https://deposit-pdbe.wwpdb.org/deposition",
    "djibouti": "https://deposit-pdbe.wwpdb.org/deposition",
    "mauritania": "https://deposit-pdbe.wwpdb.org/deposition",
    "burundi": "https://deposit-pdbe.wwpdb.org/deposition",
    "benin": "https://deposit-pdbe.wwpdb.org/deposition",
    "south africa": "https://deposit-pdbe.wwpdb.org/deposition",
    "botswana": "https://deposit-pdbe.wwpdb.org/deposition",
    "algeria": "https://deposit-pdbe.wwpdb.org/deposition",
    "swaziland": "https://deposit-pdbe.wwpdb.org/deposition",
    "madagascar": "https://deposit-pdbe.wwpdb.org/deposition",
    "morocco": "https://deposit-pdbe.wwpdb.org/deposition",
    "kenya": "https://deposit-pdbe.wwpdb.org/deposition",
    "mali": "https://deposit-pdbe.wwpdb.org/deposition",
    "comoros": "https://deposit-pdbe.wwpdb.org/deposition",
    "sao tome and principe": "https://deposit-pdbe.wwpdb.org/deposition",
    "mauritius": "https://deposit-pdbe.wwpdb.org/deposition",
    "malawi": "https://deposit-pdbe.wwpdb.org/deposition",
    "somalia": "https://deposit-pdbe.wwpdb.org/deposition",
    "senegal": "https://deposit-pdbe.wwpdb.org/deposition",
    "sierra leone": "https://deposit-pdbe.wwpdb.org/deposition",
    "seychelles": "https://deposit-pdbe.wwpdb.org/deposition",
    "uganda": "https://deposit-pdbe.wwpdb.org/deposition",
    "mozambique": "https://deposit-pdbe.wwpdb.org/deposition",
    "sudan": "https://deposit-pdbe.wwpdb.org/deposition",
    "south sudan": "https://deposit-pdbe.wwpdb.org/deposition",
    "reunion": "https://deposit-pdbe.wwpdb.org/deposition",
    "cote d'ivoire": "https://deposit-pdbe.wwpdb.org/deposition",
    "mayotte": "https://deposit-pdbe.wwpdb.org/deposition",
    "saint helena, ascension and tristan da cunha": "https://deposit-pdbe.wwpdb.org/deposition",
    "cambodia": "https://deposit-pdbj.wwpdb.org/deposition",
    "china": "https://deposit-pdbj.wwpdb.org/deposition",
    "afghanistan": "https://deposit-pdbj.wwpdb.org/deposition",
    "vietnam": "https://deposit-pdbj.wwpdb.org/deposition",
    "viet nam": "https://deposit-pdbj.wwpdb.org/deposition",
    "india": "https://deposit-pdbj.wwpdb.org/deposition",
    "malaysia": "https://deposit-pdbj.wwpdb.org/deposition",
    "indonesia": "https://deposit-pdbj.wwpdb.org/deposition",
    "laos": "https://deposit-pdbj.wwpdb.org/deposition",
    "lao people's democratic republic": "https://deposit-pdbj.wwpdb.org/deposition",
    "taiwan": "https://deposit-pdbj.wwpdb.org/deposition",
    "turkey": "https://deposit-pdbj.wwpdb.org/deposition",
    "sri lanka": "https://deposit-pdbj.wwpdb.org/deposition",
    "turkmenistan": "https://deposit-pdbj.wwpdb.org/deposition",
    "tajikistan": "https://deposit-pdbj.wwpdb.org/deposition",
    "thailand": "https://deposit-pdbj.wwpdb.org/deposition",
    "nepal": "https://deposit-pdbj.wwpdb.org/deposition",
    "pakistan": "https://deposit-pdbj.wwpdb.org/deposition",
    "philippines": "https://deposit-pdbj.wwpdb.org/deposition",
    "bangladesh": "https://deposit-pdbj.wwpdb.org/deposition",
    "brunei": "https://deposit-pdbj.wwpdb.org/deposition",
    "brunei darussalam": "https://deposit-pdbj.wwpdb.org/deposition",
    "japan": "https://deposit-pdbj.wwpdb.org/deposition",
    "bhutan": "https://deposit-pdbj.wwpdb.org/deposition",
    "hong kong": "https://deposit-pdbj.wwpdb.org/deposition",
    "kyrgyzstan": "https://deposit-pdbj.wwpdb.org/deposition",
    "uzbekistan": "https://deposit-pdbj.wwpdb.org/deposition",
    "myanmar": "https://deposit-pdbj.wwpdb.org/deposition",
    "singapore": "https://deposit-pdbj.wwpdb.org/deposition",
    "macau": "https://deposit-pdbj.wwpdb.org/deposition",
    "macao": "https://deposit-pdbj.wwpdb.org/deposition",
    "mongolia": "https://deposit-pdbj.wwpdb.org/deposition",
    "north korea": "https://deposit-pdbj.wwpdb.org/deposition",
    "korea, democratic people's republic of": "https://deposit-pdbj.wwpdb.org/deposition",
    "korea, republic of": "https://deposit-pdbj.wwpdb.org/deposition",
    "south korea": "https://deposit-pdbj.wwpdb.org/deposition",
    "maldives": "https://deposit-pdbj.wwpdb.org/deposition",
    "kazakhstan": "https://deposit-pdbj.wwpdb.org/deposition",
    "christmas island": "https://deposit-pdbj.wwpdb.org/deposition",
    "timor-leste": "https://deposit-pdbj.wwpdb.org/deposition",
    "british indian ocean territory": "https://deposit-pdbj.wwpdb.org/deposition",
    "cocos (keeling) islands": "https://deposit-pdbj.wwpdb.org/deposition",
    "oman": "https://deposit-pdbj.wwpdb.org/deposition",
    "lebanon": "https://deposit-pdbj.wwpdb.org/deposition",
    "iraq": "https://deposit-pdbj.wwpdb.org/deposition",
    "bahrain": "https://deposit-pdbj.wwpdb.org/deposition",
    "iran": "https://deposit-pdbj.wwpdb.org/deposition",
    "iran, islamic republic of": "https://deposit-pdbj.wwpdb.org/deposition",
    "yemen": "https://deposit-pdbj.wwpdb.org/deposition",
    "syria": "https://deposit-pdbj.wwpdb.org/deposition",
    "syrian arab republic": "https://deposit-pdbj.wwpdb.org/deposition",
    "qatar": "https://deposit-pdbj.wwpdb.org/deposition",
    "jordan": "https://deposit-pdbj.wwpdb.org/deposition",
    "kuwait": "https://deposit-pdbj.wwpdb.org/deposition",
    "palestinian territory": "https://deposit-pdbj.wwpdb.org/deposition",
    "united arab emirates": "https://deposit-pdbj.wwpdb.org/deposition",
    "saudi arabia": "https://deposit-pdbj.wwpdb.org/deposition",
    "guatemala": "https://deposit.wwpdb.org/deposition",
    "antigua and barbuda": "https://deposit.wwpdb.org/deposition",
    "british virgin islands": "https://deposit.wwpdb.org/deposition",
    "virgin islands, british": "https://deposit.wwpdb.org/deposition",
    "virgin islands, u.s.": "https://deposit.wwpdb.org/deposition",
    "virgin island": "https://deposit.wwpdb.org/deposition",
    "anguilla": "https://deposit.wwpdb.org/deposition",
    "canada": "https://deposit.wwpdb.org/deposition",
    "grenada": "https://deposit.wwpdb.org/deposition",
    "costa rica": "https://deposit.wwpdb.org/deposition",
    "greenland": "https://deposit.wwpdb.org/deposition",
    "cuba": "https://deposit.wwpdb.org/deposition",
    "puerto rico": "https://deposit.wwpdb.org/deposition",
    "nicaragua": "https://deposit.wwpdb.org/deposition",
    "guadeloupe": "https://deposit.wwpdb.org/deposition",
    "panama": "https://deposit.wwpdb.org/deposition",
    "dominican republic": "https://deposit.wwpdb.org/deposition",
    "dominica": "https://deposit.wwpdb.org/deposition",
    "barbados": "https://deposit.wwpdb.org/deposition",
    "haiti": "https://deposit.wwpdb.org/deposition",
    "jamaica": "https://deposit.wwpdb.org/deposition",
    "honduras": "https://deposit.wwpdb.org/deposition",
    "bahamas": "https://deposit.wwpdb.org/deposition",
    "belize": "https://deposit.wwpdb.org/deposition",
    "saint kitts and nevis": "https://deposit.wwpdb.org/deposition",
    "el salvador": "https://deposit.wwpdb.org/deposition",
    "united states": "https://deposit.wwpdb.org/deposition",
    "martinique": "https://deposit.wwpdb.org/deposition",
    "montserrat": "https://deposit.wwpdb.org/deposition",
    "cayman islands": "https://deposit.wwpdb.org/deposition",
    "saint barthelemy": "https://deposit.wwpdb.org/deposition",
    "saint lucia": "https://deposit.wwpdb.org/deposition",
    "saint vincent and the grenadines": "https://deposit.wwpdb.org/deposition",
    "sint maarten (dutch part)": "https://deposit.wwpdb.org/deposition",
    "saint martin (french part)": "https://deposit.wwpdb.org/deposition",
    "turks and caicos islands": "https://deposit.wwpdb.org/deposition",
    "bermuda": "https://deposit.wwpdb.org/deposition",
    "saint pierre and miquelon": "https://deposit.wwpdb.org/deposition",
    "mexico": "https://deposit.wwpdb.org/deposition",
    "curacao": "https://deposit.wwpdb.org/deposition",
    "aruba": "https://deposit.wwpdb.org/deposition",
    "bonaire": "https://deposit.wwpdb.org/deposition",
    "bonaire, sint eustatius and saba": "https://deposit.wwpdb.org/deposition",
    "trinidad and tobago": "https://deposit.wwpdb.org/deposition",
    "colombia": "https://deposit.wwpdb.org/deposition",
    "bolivia": "https://deposit.wwpdb.org/deposition",
    "bolivia, plurinational state of": "https://deposit.wwpdb.org/deposition",
    "venezuela": "https://deposit.wwpdb.org/deposition",
    "venezuela, bolivarian republic of": "https://deposit.wwpdb.org/deposition",
    "chile": "https://deposit.wwpdb.org/deposition",
    "suriname": "https://deposit.wwpdb.org/deposition",
    "paraguay": "https://deposit.wwpdb.org/deposition",
    "ecuador": "https://deposit.wwpdb.org/deposition",
    "french guiana": "https://deposit.wwpdb.org/deposition",
    "south georgia and the south sandwich islands": "https://deposit.wwpdb.org/deposition",
    "guyana": "https://deposit.wwpdb.org/deposition",
    "brazil": "https://deposit.wwpdb.org/deposition",
    "peru": "https://deposit.wwpdb.org/deposition",
    "uruguay": "https://deposit.wwpdb.org/deposition",
    "falkland islands": "https://deposit.wwpdb.org/deposition",
    "falkland islands (malvinas)": "https://deposit.wwpdb.org/deposition",
    "argentina": "https://deposit.wwpdb.org/deposition",
    "french southern territories": "https://deposit-pdbe.wwpdb.org/deposition",
    "bouvet island": "https://deposit-pdbe.wwpdb.org/deposition",
    "heard island and mcdonald islands": "https://deposit-pdbe.wwpdb.org/deposition",
    "antarctica": "https://deposit-pdbe.wwpdb.org/deposition",
}
